# This is a basic workflow to help you get started with Actions

name: CI
on:
  [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          format: 'YYYY-MM-DD-HH-mm'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python setup.py install

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Release_${{ steps.time.outputs.time }}
          release_name: Release_${{ steps.time.outputs.time }}
          body: Release_${{ steps.time.outputs.time }}